### ISSUE TITLE
No way to set location without being there

### ISSUE THREAD

**Issue by dgattey** [LuziferSenpai/Not-Enough-Todo#7]
Maybe this is just user error, but I can't figure out a way to arbitrarily set a location for a task without physically having the player be there when I create it. I remembered that I have to redo my tin & lead washing station, but I was all the way across the map and had to drive all the way back to set the location. Can I just ping a spot and use that instead?

**Comment by lindes** [comment]
I found the same thing (apparently) lacking.  Hmm, perhaps it's time for me to explore the factorio modding world, and see if I can't come up with a pull request... we'll see.  :)

**Comment by dgattey** [comment]
Oh there's a way better todo mod @lindes called `TaskList` - you should use that instead. There's no location based tasks but I find the whole interface way easier to use with fewer bugs for sure

**Comment by dgattey** [comment]
Also this repo & most of this person's mods seem dead 🤷
